apiVersion: v1
kind: ConfigMap
metadata:
  name: burrow-config
data:
  burrow.toml: |
    [general]
    pidfile="burrow.pid"

    [logging]
    level="debug"

    [zookeeper]
    servers=["zoo-entrance:2181"]
    timeout=30
    root-path="/burrow"

    [client-profile.burrow-kafka-profile]
    kafka-version="2.0.0"
    client-id="burrow-test"
    sasl="burrow-kafka-profile"
    tls="burrow-kafka-profile"

    [tls.burrow-kafka-profile]
    noverify=true

    [sasl.burrow-kafka-profile]
    tls=true
    username="kafka-burrow"
    password="[PASSWORD]"
    handshake-first=false
    security-protocol="SASL_SSL"
    mechanism="SCRAM-SHA-512"

    [cluster.kafka-cluster01]
    class-name="kafka"
    servers=["kafka-cluster01-kafka-external-bootstrap:9094"]
    client-profile="burrow-kafka-profile"
    topic-refresh=60
    offset-refresh=10

    [consumer.kafka-cluster01]
    class-name="kafka"
    cluster="kafka-cluster01"
    servers=["kafka-cluster01-kafka-external-bootstrap:9094"]
    client-profile="burrow-kafka-profile"
    group-denylist="^(console-consumer-|python-kafka-consumer-).*$"
    group-allowlist=""

    [consumer.kafka-cluster01_zk]
    class-name="kafka_zk"
    cluster="kafka-cluster01"
    servers=["zoo-entrance:2181"]
    zookeeper-path="/burrow"
    zookeeper-timeout=30
    group-denylist="^(console-consumer-|python-kafka-consumer-).*$"
    group-allowlist=""

    [httpserver.default]
    address=":8000"

    [storage.default]
    class-name="inmemory"
    workers=20
    intervals=15
    expire-group=604800
    min-distance=1