apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster01
  namespace: kafka-cluster
spec:
  kafka:
    version: 3.5.1
    replicas: 3
    resources:
      requests:
        memory: 1024Mi
      limits:
        memory: 1536Mi
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          class: nginx
          bootstrap:
            host: bootstrap.kafka-cluster01.your-domain.com
            annotations:
              nginx.ingress.kubernetes.io/proxy-protocol: "true"
          brokers:
            - broker: 0
              host: broker-0.kafka-cluster01.your-domain.com
            - broker: 1
              host: broker-1.kafka-cluster01.your-domain.com
            - broker: 2
              host: broker-2.kafka-cluster01.your-domain.com
          brokerCertChainAndKey:
            secretName: kafka-cluster01
            certificate: tls.crt
            key: tls.key
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.5"
      replica.fetch.max.bytes: 4194304

    storage:
      type: jbod
      volumes:
      - id: 0
        class: nfs-client
        type: persistent-claim
        size: 10Gi
        deleteClaim: true
  zookeeper:
    replicas: 3
    storage:
      class: nfs-client
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
