apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: topic-test-01
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: kafka-cluster01
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
    max.message.bytes: 4194304
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: topic-teste-02
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: kafka-cluster01
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
    max.message.bytes: 4194304